site_name: Wiki-modoki
docs_dir: 'docs'

theme:
  name: material
  custom_dir: overrides
  language: ja
  icon:
      logo: material/school
      repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
    - search.suggest
    - header.autohide
#  favicon: favicon.png

repo_url: https://github.com/Neko7sora/wiki-modoki
repo_name: Neko7sora/wiki-modoki
edit_uri: edit/develop/docs/

plugins:
  - git-revision-date
  - search:
      lang: ja

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

# Copyright
copyright: 'Portions of this content are ©2022 by individual contributors. Content available under a Creative Commons license.'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Neko7sora/wiki-modoki

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true